name: Pull From Internal develop Custom

on: workflow_dispatch

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo-sync
      run: |
        git status 
        echo "Resetting origin to: https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        git remote add tmp_upstream https://${{ secrets.PAT }}@github.com/bansalayush/internalRepo.git
        git push origin refs/remotes/tmp_upstream/develop:refs/heads/develop --force


